package manifest

import (
	"reflect"
	"testing"
)

// yarnLockClassic exercises the v1 format: scoped quoted descriptors, a
// multi-descriptor entry, an npm: alias, and — crucially — a transitive
// dependency literally named "version" inside a dependencies block, which
// must not be mistaken for the entry's own version field.
const yarnLockClassic = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@scope/tool@~3.0.0":
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/@scope/tool/-/tool-3.0.1.tgz#0a1"
  integrity sha512-AAA
  dependencies:
    version "^9.9.9"

alpha@^1.0.0, alpha@^1.0.2:
  version "1.0.3"
  resolved "https://registry.yarnpkg.com/alpha/-/alpha-1.0.3.tgz#0b2"

"myalias@npm:left-pad@^1.3.0":
  version "1.3.0"
`

// yarnLockBerry exercises the v2+ YAML format: combined descriptors in one
// key, a scoped package, an npm: alias, and workspace:/patch: entries that
// must be skipped as non-registry resolutions.
const yarnLockBerry = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"alpha@npm:^1.0.0, alpha@npm:^1.0.2":
  version: 1.0.3
  resolution: "alpha@npm:1.0.3"
  checksum: 10c0/aaa
  languageName: node
  linkType: hard

"@scope/tool@npm:~3.0.0":
  version: 3.0.1
  resolution: "@scope/tool@npm:3.0.1"

"myalias@npm:left-pad@^1.3.0":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"

"demo@workspace:.":
  version: 0.0.0-use.local
  resolution: "demo@workspace:."

"typescript@patch:typescript@npm%3A5.0.0#builtin<compat/typescript>":
  version: 5.0.0
  resolution: "typescript@patch:typescript@npm%3A5.0.0#builtin<compat/typescript>::version=5.0.0"
`

func TestParseYarnLock(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want Resolved
	}{
		{"classic v1", yarnLockClassic, Resolved{"@scope/tool": "3.0.1", "alpha": "1.0.3", "myalias": "1.3.0"}},
		{"berry", yarnLockBerry, Resolved{"@scope/tool": "3.0.1", "alpha": "1.0.3", "myalias": "1.3.0"}},
		{"classic CRLF", "alpha@^1.0.0:\r\n  version \"1.0.3\"\r\n", Resolved{"alpha": "1.0.3"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := ParseYarnLock([]byte(tc.in))
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("got %v, want %v", got, tc.want)
			}
		})
	}
}

// TestParseYarnLockConflictDropped checks that a name resolving to two
// distinct versions (conflicting transitive ranges) is omitted entirely,
// while names resolving consistently — even across separate entries — are
// kept.
func TestParseYarnLockConflictDropped(t *testing.T) {
	classic := "beta@^1.0.0:\n  version \"1.0.0\"\n\nbeta@^2.0.0:\n  version \"2.0.0\"\n\n" +
		"gamma@^1.0.0:\n  version \"1.5.0\"\n\ngamma@^1.2.0:\n  version \"1.5.0\"\n"
	berry := "__metadata:\n  version: 8\n\n\"beta@npm:^1.0.0\":\n  version: 1.0.0\n\n\"beta@npm:^2.0.0\":\n  version: 2.0.0\n\n" +
		"\"gamma@npm:^1.0.0\":\n  version: 1.5.0\n\n\"gamma@npm:^1.2.0\":\n  version: 1.5.0\n"
	want := Resolved{"gamma": "1.5.0"}
	for name, in := range map[string]string{"classic": classic, "berry": berry} {
		got, err := ParseYarnLock([]byte(in))
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("%s: got %v, want %v", name, got, want)
		}
	}
}

func TestParseYarnLockEmpty(t *testing.T) {
	for name, in := range map[string]string{
		"classic header only": "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n",
		"berry metadata only": "__metadata:\n  version: 8\n",
	} {
		got, err := ParseYarnLock([]byte(in))
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if len(got) != 0 {
			t.Errorf("%s: got %v, want empty", name, got)
		}
	}
}

func TestParseYarnLockMalformed(t *testing.T) {
	for _, in := range []string{
		"  version \"1.0.0\"\n", // classic: version field outside an entry
		"garbage\n",             // classic: unindented line that is not a header
		"__metadata: {\n",       // berry: invalid YAML
		"__metadata:\n  version: 8\n\"a@npm:^1\": 3\n",                              // berry: entry is not a mapping
		"__metadata:\n  version: 8\n\"a@npm:^1\":\n  resolution: \"a@npm:1.0.0\"\n", // berry: entry has no version
	} {
		if _, err := ParseYarnLock([]byte(in)); err == nil {
			t.Errorf("no error for %q", in)
		}
	}
}
